version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_store:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  pg_store:
