from envparse import env

CONTRACT_URL = env.str("CONTRACT_URL")
CONTRACT_ADDRESS = env.str("CONTRACT_ADDRESS")
CONTRACT_VIEWS_DATA_CACHE = env.int("CONTRACT_VIEWS_DATA_CACHE")

EXCHANGER_CONTRACT_PATH = env.str("EXCHANGER_CONTRACT_PATH")
TOKEN_CONTRACT_PATH = env.str("TOKEN_CONTRACT_PATH")
